version: "3.8"

services:
    php:
        build:
            context: .
            dockerfile: docker/dk.php.Dockerfile
        image: 'changeme/changeme-php:staging'
        restart: 'no'
        environment:
            WORDPRESS_SITE_URL: https://staging.example.com
            WORDPRESS_DB_NAME: sword_app
            WORDPRESS_DB_USER: ChangeMe
            WORDPRESS_DB_PASSWORD: ChangeMe
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_AUTH_KEY: ChangeMe
            WORDPRESS_SECURE_AUTH_KEY: ChangeMe
            WORDPRESS_LOGGED_IN_KEY: ChangeMe
            WORDPRESS_NONCE_KEY: ChangeMe
            WORDPRESS_AUTH_SALT: ChangeMe
            WORDPRESS_SECURE_AUTH_SALT: ChangeMe
            WORDPRESS_LOGGED_IN_SALT: ChangeMe
            WORDPRESS_NONCE_SALT: ChangeMe

    nginx:
        build:
            context: .
            dockerfile: docker/dk.nginx.Dockerfile
        image: 'changeme/changeme-nginx:staging'
        restart: 'no'
        depends_on:
            - php
            - traefik
        networks:
            - default
            - traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.${APP_NAME:-sword}.rule=Host(`staging.example.com`)
            - traefik.http.routers.${APP_NAME:-sword}.tls=true
            - traefik.http.routers.${APP_NAME:-sword}.entrypoints=websecure
            - traefik.http.services.${APP_NAME:-sword}.loadbalancer.server.port=80

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: 'no'
        environment:
            - MYSQL_USER=ChangeMe
            - MYSQL_PASSWORD=ChangeMe
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=sword_app
        volumes:
            - mysql_data:/var/lib/mysql

    traefik:
        image: traefik:2.9
        ports:
            - '443:443'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - traefik
        command:
            - --providers.docker
            - --providers.docker.exposedbydefault=false
            - --providers.docker.network=${PROJECT_DIR:-sword}_traefik
            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.websecure.address=:443

volumes:
    mysql_data:

networks:
    traefik:
